m = 1.  # define basic units -- output units
kN = 1.  # define basic units -- output units
sec = 1.  # define basic units -- output units
mm = m / 1000.  # define engineering units
cm = m / 100.
N = kN / 1000.
MPa = N / mm**2
GPa = MPa * 1000
m2 = m**2  # m^2
m3 = m**3  # m^3
m4 = m**4  # m^4
inch = cm * 2.54
ft = 12. * inch
g = 9.81 * m / sec**2  # gravitational acceleration
kip = 4.448 * kN
ksi = kip / inch**2
psi = ksi / 1000.
lbf = psi * inch**2 # pounds force
pcf = lbf / ft**3  # pounds per cubic foot
psf = lbf / ft**3  # pounds per square foot
in2 = inch**2  # inch^2
in4 = inch**4  # inch^4
GConc = 24.*kN / m**3  # Peso especifico del concreto
cbar = False